
name: Deploy AWS Lambda

on:
  push:
    branches: [ main ]
      
jobs:
  deploy-lambda: # <-- Name of the job
    runs-on: ubuntu-latest # Specifies the runner / virtual machine to execute the job
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        # Sets up the Python environment
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      
        # Installs any packages / dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

        # Configures AWS credentials with the keys added to GitHub repo
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

        # Zips lambda directory and updates lambda function
      - name: Deploy Lambda Function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code \
          --function-name bz-test-cicd-lambda \
          --zip-file fileb://lambda.zip